name: firecrawl
services:
  redis:
    image: redis:alpine
    restart: unless-stopped
    command: redis-server --bind 0.0.0.0
    networks:
      - firecrawl-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:3-management
    restart: unless-stopped
    networks:
      - firecrawl-network
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "check_running"]
      interval: 10s
      timeout: 5s
      retries: 5

  firecrawl-postgres:
    build: ./apps/nuq-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-firecrawl}
    networks:
      - firecrawl-network
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres || exit 1"]
      interval: 15s
      timeout: 10s
      retries: 10
      start_period: 60s

  playwright-service:
    build: ./apps/playwright-service-ts
    restart: unless-stopped
    environment:
      PORT: 3000
      BLOCK_MEDIA: ${BLOCK_MEDIA:-true}
      MAX_CONCURRENT_PAGES: ${CRAWL_CONCURRENT_REQUESTS:-3}
    networks:
      - firecrawl-network
    deploy:
      resources:
        limits:
          cpus: "0.75"
          memory: 2G
        reservations:
          memory: 1G

  api:
    build: ./apps/api
    restart: unless-stopped
    command: node dist/src/harness.js --start-docker
    ports:
      - "${PORT:-3002}:3002"
    environment:
      # Core
      HOST: 0.0.0.0
      PORT: 3002
      ENV: production
      LOGGING_LEVEL: ${LOGGING_LEVEL:-info}
      # Database - FIXED: use service name
      POSTGRES_HOST: firecrawl-postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: ${POSTGRES_DB:-firecrawl}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      # Redis
      REDIS_URL: redis://redis:6379
      REDIS_RATE_LIMIT_URL: redis://redis:6379
      # RabbitMQ
      NUQ_RABBITMQ_URL: amqp://rabbitmq:5672
      # Services
      PLAYWRIGHT_MICROSERVICE_URL: http://playwright-service:3000/scrape
      # Auth
      USE_DB_AUTHENTICATION: ${USE_DB_AUTHENTICATION:-false}
      BULL_AUTH_KEY: ${BULL_AUTH_KEY:-changeme}
      # Workers
      NUM_WORKERS_PER_QUEUE: 1
      MAX_CONCURRENT_JOBS: 1
      CRAWL_CONCURRENT_REQUESTS: 3
      BROWSER_POOL_SIZE: 1
      # Search
      SEARCH_ENGINE: ${SEARCH_ENGINE:-google}
      GOOGLE_API_KEY: ${GOOGLE_API_KEY}
      GOOGLE_CX: ${GOOGLE_CX}
    depends_on:
      redis:
        condition: service_healthy
      firecrawl-postgres:  # FIXED: use correct service name
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      playwright-service:
        condition: service_started
    networks:
      - firecrawl-network
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 4G
        reservations:
          memory: 2G

networks:
  firecrawl-network:
    driver: bridge

volumes:
  postgres-data:
  rabbitmq-data:
